#!/usr/bin/env python3
"""Zarvis 초기 스킬 시드 데이터를 생성해 skills.json에 씁니다."""
import json
from pathlib import Path

SKILLS = [
    # ── 생산성 ──────────────────────────────────────────
    {"command": "/plan", "description": "하루 계획", "prompt": "오늘 해야 할 일을 바탕으로 현실적인 하루 계획을 세워줘. 우선순위와 시간 배분을 포함해서.", "category": "생산성", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/weekly", "description": "주간 계획", "prompt": "이번 주 목표와 할 일을 바탕으로 요일별 주간 계획을 세워줘. 버퍼 시간도 포함해줘.", "category": "생산성", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/prioritize", "description": "우선순위 정리", "prompt": "다음 할 일 목록을 긴급성과 중요성 기준으로 우선순위를 매겨줘. 아이젠하워 매트릭스로 분류해줘: {task_list}", "category": "생산성", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/focus", "description": "방해 요소 제거", "prompt": "내가 집중력을 잃는 상황: {situation}. 방해 요소를 제거하고 딥 포커스 상태를 만드는 구체적인 방법을 알려줘.", "category": "생산성", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/automate", "description": "자동화 아이디어", "prompt": "내가 반복하는 업무: {task}. 이것을 자동화할 수 있는 아이디어 5가지를 도구와 방법 포함해서 알려줘.", "category": "생산성", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/delegate", "description": "위임할 일 정리", "prompt": "내 업무 중 위임 가능한 것들을 골라줘. 업무 목록: {task_list}. 위임 기준과 인수인계 방법도 알려줘.", "category": "생산성", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/habits", "description": "습관 만들기", "prompt": "만들고 싶은 습관: {habit}. 이 습관을 30일 안에 정착시키기 위한 단계별 계획을 세워줘. 스택킹 방법도 포함해줘.", "category": "생산성", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/track", "description": "추적 시스템", "prompt": "목표: {goal}. 이 목표의 진행 상황을 추적할 수 있는 측정 지표와 추적 시스템을 설계해줘.", "category": "생산성", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/timeblock", "description": "시간 블로킹", "prompt": "다음 할 일들을 시간 블록으로 배치해줘. 집중 블록(2h), 관리 블록(1h), 휴식 블록(30m) 단위로 구성해줘: {tasks}", "category": "생산성", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/review", "description": "주간 회고", "prompt": "이번 주 돌아보기: 잘한 것, 못한 것, 다음 주 개선할 것을 구조적으로 회고할 수 있도록 질문을 던져줘.", "category": "생산성", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/morningroutine", "description": "하루를 시작하는 루틴", "prompt": "기상 후 1시간 안에 하루를 최고의 상태로 시작할 수 있는 모닝 루틴을 설계해줘. 내 목표: {goal}", "category": "생산성", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/batchtasks", "description": "비슷한 작업 묶기", "prompt": "다음 할 일들을 유사한 유형끼리 묶어서 배치 처리할 수 있도록 그룹화해줘: {tasks}", "category": "생산성", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    # ── 콘텐츠 제작 ─────────────────────────────────────
    {"command": "/ideas", "description": "콘텐츠 아이디어", "prompt": "주제: {topic}. 이 주제로 SNS, 유튜브, 블로그에서 바이럴될 수 있는 콘텐츠 아이디어 10개를 생성해줘.", "category": "콘텐츠 제작", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/hooks", "description": "바이럴 후킹 문구", "prompt": "주제: {topic}. 첫 3초 안에 멈추게 만드는 후킹 문구 10개를 써줘. 숫자, 반전, 질문 형식으로 다양하게.", "category": "콘텐츠 제작", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/scripts", "description": "전체 스크립트", "prompt": "주제: {topic}, 길이: {duration}분, 채널 톤: {tone}. 인트로-본론-아웃트로 구조의 완성된 영상 스크립트를 써줘.", "category": "콘텐츠 제작", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/captions", "description": "캡션 작성", "prompt": "다음 콘텐츠에 맞는 SNS 캡션을 써줘. 플랫폼: {platform}, 톤: {tone}, 해시태그 포함. 내용: {content}", "category": "콘텐츠 제작", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/carousel", "description": "카드뉴스 콘텐츠", "prompt": "주제: {topic}. 7장짜리 카드뉴스 콘텐츠를 만들어줘. 각 슬라이드 제목과 본문(50자 이내), 마지막 CTA 포함.", "category": "콘텐츠 제작", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/reels", "description": "릴스 아이디어", "prompt": "주제: {topic}. 15-30초 숏폼 릴스 아이디어 5개를 씬 구성, 후킹 포인트, 배경음악 스타일까지 포함해서 써줘.", "category": "콘텐츠 제작", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/youtube", "description": "유튜브 영상 아이디어", "prompt": "채널 주제: {channel_topic}. 조회수가 높을 유튜브 영상 아이디어 5개를 제목, 썸네일 방향, 예상 타깃까지 포함해서 제안해줘.", "category": "콘텐츠 제작", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/threads", "description": "트위터/X 스레드", "prompt": "주제: {topic}. 10개 트윗으로 구성된 바이럴 스레드를 써줘. 첫 트윗이 후킹, 마지막이 CTA가 되도록.", "category": "콘텐츠 제작", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/blog", "description": "블로그 글", "prompt": "주제: {topic}, 타깃: {audience}. SEO 최적화된 블로그 글을 써줘. 소제목, 본문 1500자 이상, 결론 포함.", "category": "콘텐츠 제작", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/seo", "description": "콘텐츠 SEO 최적화", "prompt": "다음 콘텐츠를 SEO 관점에서 최적화해줘. 핵심 키워드 추출, 제목 개선, 메타 디스크립션 작성 포함: {content}", "category": "콘텐츠 제작", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/headlines", "description": "제목 아이디어", "prompt": "주제: {topic}. 클릭률이 높을 제목 10개를 써줘. 숫자형, 질문형, 방법형, 반전형 등 다양한 형식으로.", "category": "콘텐츠 제작", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/repurpose", "description": "콘텐츠 재활용", "prompt": "원본 콘텐츠: {content}. 이것을 인스타그램 카드뉴스, 트위터 스레드, 유튜브 쇼츠 스크립트로 각각 변환해줘.", "category": "콘텐츠 제작", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    # ── 비즈니스/전략 ────────────────────────────────────
    {"command": "/idea", "description": "비즈니스 아이디어 생성", "prompt": "분야: {field}, 내 강점: {strengths}. 수익화 가능한 비즈니스 아이디어 5개를 시장 규모, 진입 장벽, 수익 모델까지 포함해서 제안해줘.", "category": "비즈니스/전략", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/validate", "description": "아이디어 검증", "prompt": "비즈니스 아이디어: {idea}. 이 아이디어를 실제 돈 쓰지 않고 2주 안에 검증할 수 있는 실험 3가지를 설계해줘.", "category": "비즈니스/전략", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/businessplan", "description": "전체 사업계획서", "prompt": "사업 아이디어: {idea}. 투자자에게 보여줄 수 있는 사업계획서를 써줘. 문제/솔루션/시장/수익모델/팀/로드맵 포함.", "category": "비즈니스/전략", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/gtm", "description": "시장 진입 전략", "prompt": "제품: {product}, 타깃 시장: {market}. 첫 100명의 고객을 획득하기 위한 Go-To-Market 전략을 단계별로 세워줘.", "category": "비즈니스/전략", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/pricing", "description": "가격 전략", "prompt": "제품/서비스: {product}, 원가: {cost}, 경쟁사 가격: {competitor_price}. 최적의 가격 전략과 가격대를 3가지 시나리오로 제안해줘.", "category": "비즈니스/전략", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/revenue", "description": "수익 모델", "prompt": "비즈니스: {business}. 적용 가능한 수익 모델 5가지를 각각의 장단점, 적합한 단계, 예상 수익성 포함해서 분석해줘.", "category": "비즈니스/전략", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/costcut", "description": "비용 절감", "prompt": "현재 지출 내역: {expenses}. 퀄리티를 유지하면서 30% 비용을 줄일 수 있는 방법을 구체적으로 알려줘.", "category": "비즈니스/전략", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/growth", "description": "성장 전략", "prompt": "현재 비즈니스 상태: {status}. 6개월 안에 매출 2배를 달성하기 위한 성장 전략을 채널별로 세워줘.", "category": "비즈니스/전략", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/scaling", "description": "비즈니스 확장", "prompt": "현재 비즈니스: {business}. 사람을 더 고용하지 않고 수익을 3배로 확장할 수 있는 시스템화 방법을 알려줘.", "category": "비즈니스/전략", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/positioning", "description": "브랜드 포지셔닝", "prompt": "제품/서비스: {product}, 경쟁사: {competitors}. 차별화된 포지셔닝 전략과 핵심 메시지를 3가지 방향으로 제안해줘.", "category": "비즈니스/전략", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/usp", "description": "고유 강점", "prompt": "내 비즈니스: {business}, 경쟁사 대비 강점: {strengths}. 고객이 나를 선택해야 하는 이유를 한 문장으로 정리해줘. USP 10개 옵션 제시.", "category": "비즈니스/전략", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/competition", "description": "경쟁사 분석", "prompt": "경쟁사: {competitors}. 각 경쟁사의 강점/약점/포지셔닝/가격을 분석하고 내가 공략할 수 있는 빈틈을 찾아줘.", "category": "비즈니스/전략", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    # ── 퍼스널 브랜딩 ────────────────────────────────────
    {"command": "/niche", "description": "니치 정의", "prompt": "내 전문성: {expertise}, 관심사: {interests}, 타깃: {target}. 수익화 가능하고 경쟁이 적은 니치 3가지를 추천해줘.", "category": "퍼스널 브랜딩", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/audience", "description": "타깃 오디언스", "prompt": "내 콘텐츠/서비스: {content}. 이상적인 타깃 오디언스 페르소나 3개를 나이, 직업, 고민, 원하는 것, 소비 채널까지 구체적으로 만들어줘.", "category": "퍼스널 브랜딩", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/bio", "description": "프로필 소개 최적화", "prompt": "내 배경: {background}, 전문성: {expertise}, 타깃: {audience}. 인스타그램, 링크드인, 트위터용 프로필 소개를 각각 써줘.", "category": "퍼스널 브랜딩", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/voice", "description": "브랜드 보이스", "prompt": "내 브랜드: {brand}, 타깃: {audience}. 나만의 말투와 브랜드 보이스를 정의해줘. 해야 할 말투, 하지 말아야 할 말투, 예시 포함.", "category": "퍼스널 브랜딩", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/story", "description": "개인 스토리", "prompt": "내 경험: {experience}. 사람들이 공감하고 기억하는 퍼스널 브랜드 스토리를 써줘. 전환점, 교훈, 지금의 나 연결.", "category": "퍼스널 브랜딩", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/authority", "description": "권위 구축", "prompt": "내 분야: {field}, 현재 자격: {credentials}. 6개월 안에 해당 분야 전문가로 인식되기 위한 권위 구축 전략을 알려줘.", "category": "퍼스널 브랜딩", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/consistency", "description": "꾸준한 발행 시스템", "prompt": "내 콘텐츠 채널: {channels}, 가용 시간: 주 {hours}시간. 번아웃 없이 꾸준히 발행할 수 있는 콘텐츠 시스템을 설계해줘.", "category": "퍼스널 브랜딩", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/monetize", "description": "수익화 아이디어", "prompt": "내 전문성: {expertise}, 팔로워 수: {followers}. 퍼스널 브랜드를 수익화할 수 있는 방법 10가지를 단기/중기/장기로 나눠서 알려줘.", "category": "퍼스널 브랜딩", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/network", "description": "네트워킹 전략", "prompt": "내 목표: {goal}, 분야: {field}. 온라인·오프라인에서 의미 있는 네트워크를 만들기 위한 90일 네트워킹 전략을 세워줘.", "category": "퍼스널 브랜딩", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/contentplan", "description": "콘텐츠 전략", "prompt": "내 브랜드: {brand}, 타깃: {audience}, 채널: {channels}. 한 달치 콘텐츠 캘린더와 각 포스트의 방향을 잡아줘.", "category": "퍼스널 브랜딩", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    # ── 코딩/기술 ────────────────────────────────────────
    {"command": "/debug", "description": "버그 찾기", "prompt": "다음 코드에서 버그를 찾아줘. 원인과 수정 방법을 단계별로 설명해줘:\n\n```\n{code}\n```", "category": "코딩/기술", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/refactor", "description": "코드 정리", "prompt": "다음 코드를 가독성, 유지보수성, SOLID 원칙 기준으로 리팩토링해줘. 변경 이유도 설명해줘:\n\n```\n{code}\n```", "category": "코딩/기술", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/optimizecode", "description": "성능 개선", "prompt": "다음 코드의 성능을 개선해줘. 시간 복잡도, 공간 복잡도 분석과 최적화된 버전을 제시해줘:\n\n```\n{code}\n```", "category": "코딩/기술", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/systemdesign", "description": "아키텍처 설계", "prompt": "시스템: {system}. 요구사항: {requirements}. 확장 가능한 시스템 아키텍처를 설계해줘. 컴포넌트 다이어그램과 설계 결정 이유 포함.", "category": "코딩/기술", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/api", "description": "API 구조 설계", "prompt": "서비스: {service}. RESTful API 엔드포인트를 설계해줘. URL, HTTP 메서드, 요청/응답 예시, 에러 코드 포함.", "category": "코딩/기술", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/database", "description": "DB 설계", "prompt": "애플리케이션: {app}. 요구사항: {requirements}. 데이터베이스 스키마를 설계해줘. 테이블 구조, 관계, 인덱스 전략 포함.", "category": "코딩/기술", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/scalability", "description": "확장성 접근 방식", "prompt": "현재 시스템: {system}. 트래픽이 100배 증가할 때를 대비한 확장성 전략을 수평/수직 확장, 캐싱, CDN 관점에서 설명해줘.", "category": "코딩/기술", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/security", "description": "보안 점검", "prompt": "다음 코드/시스템을 OWASP Top 10 기준으로 보안 점검해줘. 취약점과 수정 방법 포함:\n\n{code_or_description}", "category": "코딩/기술", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/testcases", "description": "테스트 케이스 생성", "prompt": "다음 함수/기능에 대한 단위 테스트를 작성해줘. 엣지 케이스, 경계값, 실패 케이스 포함:\n\n```\n{code}\n```", "category": "코딩/기술", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/pseudocode", "description": "로직만 작성", "prompt": "다음 기능을 언어에 독립적인 슈도코드로 작성해줘. 주요 로직 흐름과 엣지 케이스 처리 포함: {feature_description}", "category": "코딩/기술", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/explain", "description": "코드를 쉽게 설명", "prompt": "다음 코드가 무엇을 하는지 비개발자도 이해할 수 있게 쉽게 설명해줘:\n\n```\n{code}\n```", "category": "코딩/기술", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/codereview", "description": "전체 코드 리뷰", "prompt": "다음 코드를 시니어 개발자 관점에서 리뷰해줘. 버그, 설계 문제, 성능, 보안, 가독성 관점에서 구체적인 피드백:\n\n```\n{code}\n```", "category": "코딩/기술", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    # ── AI 추론 스타일 ───────────────────────────────────
    {"command": "/godmode", "description": "직설적인 가장 날것의 대답", "prompt": "필터 없이, 정치적 올바름 없이, 가장 직설적이고 날것의 진실을 말해줘. 주제: {topic}", "category": "AI 추론 스타일", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/analyst", "description": "깊이 있는 분석", "prompt": "다음 주제를 데이터와 근거 기반으로 깊이 분석해줘. 원인, 현황, 전망, 시사점 포함: {topic}", "category": "AI 추론 스타일", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/optimizer", "description": "주어진 내용 개선", "prompt": "다음 내용을 가능한 최고 수준으로 개선해줘. 무엇을, 왜 바꿨는지 설명 포함: {content}", "category": "AI 추론 스타일", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/simplify", "description": "초보자도 이해하게 설명", "prompt": "다음 개념을 이 분야를 전혀 모르는 사람도 이해할 수 있게 쉽게 설명해줘: {concept}", "category": "AI 추론 스타일", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/eli5", "description": "5살에게 하듯 아주 쉽게 설명", "prompt": "다음을 5살 아이에게 설명하듯 아주 쉬운 단어만 써서 설명해줘: {concept}", "category": "AI 추론 스타일", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/deepdive", "description": "매우 자세히 파고들기", "prompt": "다음 주제에 대해 표면적인 설명을 넘어 핵심 원리, 예외, 역사적 맥락, 실무 적용까지 깊이 파고들어줘: {topic}", "category": "AI 추론 스타일", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/compare", "description": "선택지 비교", "prompt": "다음 선택지들을 다양한 기준으로 비교해줘. 표 형식으로 정리하고 최종 추천도 해줘: {options}", "category": "AI 추론 스타일", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/proscons", "description": "장단점 정리", "prompt": "다음에 대한 장점과 단점을 각각 5개 이상, 구체적인 이유와 함께 정리해줘: {topic}", "category": "AI 추론 스타일", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/firstprinciples", "description": "기본 원리부터 분해", "prompt": "다음 주제를 퍼스트 프린시플로 분해해줘. 가장 기본적인 사실에서 시작해서 논리적으로 재조립해줘: {topic}", "category": "AI 추론 스타일", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/contrarian", "description": "아이디어에 반대 관점 제시", "prompt": "다음 아이디어/주장에 대한 반대 관점을 논리적으로 제시해줘. 일반적 통념을 뒤집는 시각으로: {idea}", "category": "AI 추론 스타일", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/devil", "description": "반대편 입장에서 주장", "prompt": "악마의 변호인 역할을 해줘. 다음 주장에 대해 최대한 강력한 반론을 펼쳐줘: {argument}", "category": "AI 추론 스타일", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/steelman", "description": "주장의 가장 강력한 버전 만들기", "prompt": "다음 주장의 가장 강력하고 설득력 있는 버전을 만들어줘. 약점을 보완하고 논리를 강화해줘: {argument}", "category": "AI 추론 스타일", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    # ── 실행/출력 모드 ───────────────────────────────────
    {"command": "/ghost", "description": "최종 답변만, 설명 없음", "prompt": "지금부터 내 요청에 대해 최종 결과물만 출력해줘. 설명, 주석, 서론, AI 티를 모두 제거하고 결과만: {request}", "category": "실행/출력 모드", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/minimal", "description": "가능한 가장 짧은 답변", "prompt": "최대한 짧게 핵심만 답해줘: {question}", "category": "실행/출력 모드", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/brief", "description": "최대 3~5줄", "prompt": "3-5줄 이내로 요약해서 답해줘: {question}", "category": "실행/출력 모드", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/expand", "description": "자세한 설명", "prompt": "다음 내용을 가능한 상세하게 확장해서 설명해줘. 예시, 맥락, 배경 모두 포함: {content}", "category": "실행/출력 모드", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/stepbystep", "description": "단계별 설명", "prompt": "다음을 초보자도 따라할 수 있도록 단계별로 설명해줘. 각 단계마다 왜 그렇게 하는지도 포함: {task}", "category": "실행/출력 모드", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/checklist", "description": "실행 가능한 체크리스트", "prompt": "다음에 대한 실행 가능한 체크리스트를 만들어줘. 각 항목은 구체적인 행동으로: {goal}", "category": "실행/출력 모드", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/framework", "description": "구조화된 프레임워크", "prompt": "다음 문제/목표를 해결하기 위한 구조화된 프레임워크를 만들어줘: {problem}", "category": "실행/출력 모드", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/blueprint", "description": "실행 설계안", "prompt": "다음을 실행하기 위한 상세한 블루프린트를 만들어줘. 필요한 자원, 단계, 예상 결과 포함: {goal}", "category": "실행/출력 모드", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/playbook", "description": "반복 가능한 시스템", "prompt": "다음을 반복 가능한 플레이북으로 만들어줘. 누구든 따라할 수 있도록 SOP 형식으로: {process}", "category": "실행/출력 모드", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/roadmap", "description": "일정 기반 단계 계획", "prompt": "목표: {goal}. 3개월/6개월/1년 타임라인으로 로드맵을 만들어줘. 마일스톤과 핵심 지표 포함.", "category": "실행/출력 모드", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/draft", "description": "초안 작성", "prompt": "다음에 대한 첫 번째 초안을 완성도 70% 수준으로 빠르게 작성해줘: {content}", "category": "실행/출력 모드", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/polish", "description": "깔끔하게 다듬기", "prompt": "다음 내용을 전문적이고 깔끔하게 다듬어줘. 문장 구조, 흐름, 어조를 개선해줘:\n\n{content}", "category": "실행/출력 모드", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    # ── 커리어/직업 ─────────────────────────────────────
    {"command": "/resume", "description": "이력서 작성", "prompt": "내 경력: {experience}. ATS를 통과하고 채용담당자 눈에 띄는 이력서를 써줘. 성과 중심으로 수치 포함.", "category": "커리어/직업", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/coverletter", "description": "자기소개서 작성", "prompt": "회사: {company}, 직무: {role}, 내 강점: {strengths}. 채용담당자가 끝까지 읽을 자기소개서를 써줘.", "category": "커리어/직업", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/interview", "description": "면접 준비", "prompt": "회사: {company}, 직무: {role}. 이 면접을 통과하기 위한 준비 전략과 예상 질문 10개를 알려줘.", "category": "커리어/직업", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/questions", "description": "면접 질문", "prompt": "직무: {role}, 회사: {company}. 이 포지션에서 나올 수 있는 면접 질문 20개를 기술/행동/상황 질문으로 나눠서 알려줘.", "category": "커리어/직업", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/answers", "description": "강력한 답변 작성", "prompt": "면접 질문: {question}. STAR 방식으로 강력한 답변을 써줘. 내 경험: {experience}", "category": "커리어/직업", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/portfolio", "description": "포트폴리오 아이디어", "prompt": "직무: {role}, 내 프로젝트: {projects}. 채용담당자에게 임팩트 있는 포트폴리오를 구성하는 방법을 알려줘.", "category": "커리어/직업", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/linkedin", "description": "링크드인 최적화", "prompt": "내 직무: {role}, 경력: {experience}. 링크드인 프로필을 최적화해줘. 헤드라인, 요약, 경력 기술 포함.", "category": "커리어/직업", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/apply", "description": "지원 전략", "prompt": "목표 회사: {companies}, 내 현재 스펙: {profile}. 합격 가능성을 높이기 위한 90일 취업 전략을 세워줘.", "category": "커리어/직업", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/negotiate", "description": "연봉 협상", "prompt": "현재 연봉: {current}, 목표 연봉: {target}, 회사 오퍼: {offer}. 연봉 협상에서 쓸 수 있는 구체적인 스크립트를 써줘.", "category": "커리어/직업", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/skillgap", "description": "스킬 갭 분석", "prompt": "목표 직무: {role}, 내 현재 스킬: {skills}. 갭 분석을 해주고 부족한 스킬을 채울 수 있는 학습 계획을 세워줘.", "category": "커리어/직업", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/careerpath", "description": "커리어 로드맵", "prompt": "현재 직무: {current_role}, 목표: {goal}. 5년 커리어 로드맵을 단계별 역할, 필요 스킬, 네트워킹 전략으로 그려줘.", "category": "커리어/직업", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/freelance", "description": "프리랜서 로드맵", "prompt": "내 스킬: {skills}. 직장을 다니면서 프리랜서를 시작해서 6개월 안에 월 {target_income}을 버는 로드맵을 만들어줘.", "category": "커리어/직업", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    # ── 학습 ────────────────────────────────────────────
    {"command": "/learn", "description": "어떤 주제든 학습", "prompt": "주제: {topic}. 이것을 처음 배우는 사람이 핵심을 빠르게 파악할 수 있도록 설명해줘.", "category": "학습", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/learningplan", "description": "학습 로드맵", "prompt": "주제: {topic}, 목표 수준: {level}, 가용 시간: 주 {hours}시간. 8주 학습 로드맵을 주별 계획으로 만들어줘.", "category": "학습", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/resources", "description": "최고의 자료 추천", "prompt": "주제: {topic}. 무료/유료 최고의 학습 자료를 책, 강의, 유튜브, 블로그, 커뮤니티로 나눠서 추천해줘.", "category": "학습", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/books", "description": "추천 도서", "prompt": "주제: {topic}. 이 분야를 마스터하기 위해 반드시 읽어야 할 책 5권을 입문/심화로 나눠서 추천해줘. 핵심 내용도 요약해줘.", "category": "학습", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/courses", "description": "추천 강의", "prompt": "주제: {topic}, 현재 수준: {level}. 유데미, 코세라, 유튜브에서 최고의 강의를 3개 추천해줘. 각각 장단점과 예상 학습 시간 포함.", "category": "학습", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/practice", "description": "연습 계획", "prompt": "스킬: {skill}. 의도적 연습 방법으로 30일 안에 실력을 확 올릴 수 있는 일별 연습 계획을 만들어줘.", "category": "학습", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/quiz", "description": "지식 테스트", "prompt": "주제: {topic}. 내 이해도를 테스트할 수 있는 퀴즈 10개를 난이도 순으로 만들어줘. 정답과 설명 포함.", "category": "학습", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/flashcards", "description": "암기 카드", "prompt": "주제: {topic}. 핵심 개념 20개를 앞면(질문)/뒷면(답변) 형식의 플래시카드로 만들어줘.", "category": "학습", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/summary", "description": "주제 요약", "prompt": "다음 내용의 핵심을 20% 분량으로 요약해줘. 가장 중요한 포인트 5개를 불릿으로 정리: {content}", "category": "학습", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/teach", "description": "설명하며 배우기", "prompt": "나는 {topic}을 배우고 있어. 내가 이해한 것을 설명할게. 틀린 부분과 보완할 점을 알려줘: {my_explanation}", "category": "학습", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/revision", "description": "복습 시스템", "prompt": "주제: {topic}. 망각 곡선에 맞춘 간격 반복 복습 계획을 만들어줘. 1일/3일/7일/14일/30일 후 복습 내용 포함.", "category": "학습", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    # ── 고급 프롬프트 제어 ──────────────────────────────
    {"command": "/role", "description": "역할 지정", "prompt": "지금부터 너는 {role} 역할이야. 이 역할로 다음 질문에 답해줘: {question}", "category": "고급 프롬프트 제어", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/context", "description": "맥락 제공", "prompt": "배경: {background}. 이 맥락을 바탕으로 다음 질문에 답해줘: {question}", "category": "고급 프롬프트 제어", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/constraints", "description": "제한 조건 설정", "prompt": "제한 조건: {constraints}. 이 조건 안에서만 다음 요청을 처리해줘: {request}", "category": "고급 프롬프트 제어", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/format", "description": "출력 형식 지정", "prompt": "다음 요청의 결과를 {format} 형식으로 출력해줘: {request}", "category": "고급 프롬프트 제어", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/tone", "description": "말투 선택", "prompt": "{tone} 톤으로 다음 내용을 작성해줘: {content}", "category": "고급 프롬프트 제어", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/style", "description": "글쓰기 스타일 지정", "prompt": "{style} 스타일로 다음 내용을 다시 써줘: {content}", "category": "고급 프롬프트 제어", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/examples", "description": "예시 제공", "prompt": "다음 개념을 {count}가지 실제 예시로 설명해줘: {concept}", "category": "고급 프롬프트 제어", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/iterate", "description": "답변 개선", "prompt": "이전 답변을 바탕으로 다음 피드백을 반영해서 개선해줘: {feedback}", "category": "고급 프롬프트 제어", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/critic", "description": "자기 비판 검토", "prompt": "방금 네가 한 답변의 문제점과 개선할 수 있는 부분을 스스로 비판해줘.", "category": "고급 프롬프트 제어", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/refine", "description": "결과물 다듬기", "prompt": "다음 결과물을 전문가 수준으로 다듬어줘. 구체적으로 무엇을 왜 바꿨는지도 설명: {content}", "category": "고급 프롬프트 제어", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
    {"command": "/retry", "description": "다시 생성", "prompt": "이전 답변이 마음에 들지 않아. 완전히 다른 방향으로 다시 생성해줘.", "category": "고급 프롬프트 제어", "platforms": ["claude", "chatgpt"], "source": "zarvis"},
]

output_path = Path(__file__).parent.parent / "skills.json"
output_path.write_text(json.dumps(SKILLS, ensure_ascii=False, indent=2))
print(f"Wrote {len(SKILLS)} skills to {output_path}")
